### ISSUE TITLE
redux-helper doesn't work with react-navigation 2.3.0

### ISSUE THREAD

**Issue by Freddy03h** [react-navigation/react-navigation-redux-helpers#36]
`TypeError: navigation.getChildNavigation is not a function`

I think it's because `createNavigationPropConstructor`doesn't use `createNavigator` from `react-navigation`, so the created `navigation` object don't get all needed functions `react-navigation` expect to be presents.

**Comment by proutek** [comment]
I just spent 2 hours debugging this issue when integrating navigation into redux.

16:32:36: Error: TypeError: TypeError: undefined is not a function (evaluating 'navigation.getChildNavigation(route.key)')

This error is located at:
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:383)
    in NavigationContainer (at mainNavigator.js:131)
    in LocaleMainNavigator (created by Connect(LocaleMainNavigator))
    in Connect(LocaleMainNavigator) (created by Connect(Connect(LocaleMainNavigator)))
    in Connect(Connect(LocaleMainNavigator)) (at mainApp.js:19)
    in RCTView (at View.js:60)
    in View (at mainApp.js:10)
    in MainApp (created by Connect(MainApp))
    in Connect(MainApp) (at appSetup.js:39)
    in PersistGate (at appSetup.js:37)
    in Provider (at appSetup.js:36)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

**Comment by proutek** [comment]
Just tried version 2.2.5 of react navigation and it works just fine.

**Comment by Freddy03h** [comment]
More informations on this thread : https://github.com/react-navigation/react-navigation/issues/4481

**Comment by Ashoat** [comment]
Okay, `react-navigation-redux-helpers@2.0.0-beta.0` has been released under the `@beta` tag, and it should solve this issue.

I'll try and put up a real `react-navigation-redux-helpers@2.0.0` later today that should simply things. Instead of `initializeListeners`, `createNavigationPropConstructor`, `createReduxBoundAddListener`, and `createDidUpdateCallback`, we'll just have a simple `reduxifyNavigator` HOC that wraps your root navigator, and takes `dispatch` and `navigation` state as props.
